const FETCH_POSTS_START = "FETCH_POSTS_START"; 
const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS"; 
const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE"; 
const FETCH_POST_START = "FETCH_POST_START"; 
const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"; 
const FETCH_POST_FAILURE = "FETCH_POST_FAILURE"; 

export {
    FETCH_POSTS_START,
    FETCH_POSTS_SUCCESS,
    FETCH_POSTS_FAILURE,
    FETCH_POST_START,
    FETCH_POST_SUCCESS,
    FETCH_POST_FAILURE
};
