export const FETCH_PEOPLE_START = "FETCH_PEOPLE_START"; 
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS"; 
export const FETCH_PEOPLE_FAILURE = "FETCH_PEOPLE_FAILURE";

export const FETCH_PEOPLE_BY_SEARCH_START = 'FETCH_PEOPLE_BY_SEARCH_START';
export const FETCH_PEOPLE_BY_SEARCH_SUCCESS = 'FETCH_PEOPLE_BY_SEARCH_SUCCESS';
export const FETCH_PEOPLE_BY_SEARCH_FAILURE = 'FETCH_PEOPLE_BY_SEARCH_FAILURE';